AWSTemplateFormatVersion: 2010-09-09

Resources:
  SaiyoTemporaryIamPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Action: ec2:*
            Resources: '*'
            Condition:
              StringEquals:
                "ec2:ResourceTag/pjt": "saiyo"
          - Effect: Deny
            Action: dynamodb:*Item
            Resources:
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/saiyo-queue
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/saiyo-interviewee
          - Effect: Deny
            Action:
              - dynamodb:Scan
              - dynamodb:Query
            Resources:
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/saiyo-queue
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/saiyo-queue/index/*
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/saiyo-interviewee
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/saiyo-interviewee/index/*
          - Effect: Deny
            Action: s3:*Item
            Resources:
              - arn:aws:s3:::saiyo-interviewee/*
              - arn:aws:s3:::saiyo-face/*
          - Effect: Deny
            Action: s3:*Bucket
            Resources:
              - arn:aws:s3:::saiyo-interviewee
              - arn:aws:s3:::saiyo-face
      PolicyName: saiyo-temporary-iam-policy
      
  SaiyoTemporaryIamGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: saiyo-temporary-iam-group
      ManagedPolicyArns:
        - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/${SaiyoTemporaryIamPolicy}