AWSTemplateFormatVersion: 2010-09-09

Resources:
  SaiyoTemporaryIamPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Temporary policy for denying access to Saiyo resources
      ManagedPolicyName: saiyo-temporary-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Action: ec2:*
            Resource: '*'
            Condition:
              StringEquals:
                "ec2:ResourceTag/pjt": "saiyo"
          - Effect: Deny
            Action: dynamodb:*Item
            Resource: 
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/saiyo-queue
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/saiyo-interviewee
          - Effect: Deny
            Action:
              - dynamodb:Scan
              - dynamodb:Query
            Resource:
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/saiyo-queue
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/saiyo-queue/index/*
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/saiyo-interviewee
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/saiyo-interviewee/index/*
          - Effect: Deny
            Action: s3:*Item
            Resource:
              - arn:aws:s3:::saiyo-face/*
              - arn:aws:s3:::saiyo-interviewee/*
          - Effect: Deny
            Action: s3:*Bucket
            Resource:
              - arn:aws:s3:::saiyo-face
              - arn:aws:s3:::saiyo-interviewee
